name: Bug Report
description: Report a bug in the Arduino to Codespaces Bridge extension
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running the extension?
      options:
        - GitHub Codespaces
        - VS Code Desktop (Windows)
        - VS Code Desktop (macOS)
        - VS Code Desktop (Linux)
        - Other
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: Run `code --version` or check Help > About
      placeholder: "1.85.0"
    validations:
      required: false

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Check in Extensions view
      placeholder: "1.0.0"
    validations:
      required: false

  - type: input
    id: board
    attributes:
      label: Arduino Board (if applicable)
      description: What board were you using?
      placeholder: "Arduino Uno R4 WiFi"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        Please paste any relevant error logs from:
        - Output panel (Arduino Bridge channel)
        - Developer Tools console (Help > Toggle Developer Tools)
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have tried reloading VS Code
          required: false
        - label: I have tried reinstalling the extension
          required: false
