name: Feature Request
description: Suggest a new feature for the Arduino to Codespaces Bridge extension
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: What part of the extension does this relate to?
      options:
        - Web Serial / Board Communication
        - Compilation
        - Upload / Flashing
        - Library Management
        - Board Management
        - Serial Monitor
        - Serial Plotter
        - IntelliSense / Code Completion
        - Environment Sync / Config
        - UI / Sidebar Views
        - Commands / Palette
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important for my workflow
        - Critical blocker
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false
